### ISSUE TITLE
List index out of range error on startup

### ISSUE THREAD

**Issue by Kumonorei** [Kumonorei/lothariel#1]
There is a list index out of range error occurring on program initialization. This is not happening every time. 

This seems to be something to so with the dungeon generation, however I could only reproduce the error on Linux, and have not yet experienced this in Windows.

* update - This has now been reproduced under Windows.

Traceback (most recent call last):
  File "E:\Python\lothariel\lothariel.py", line 282, in <module>
    make_map()
  File "E:\Python\lothariel\lothariel.py", line 153, in make_map
    create_room(new_room)
  File "E:\Python\lothariel\lothariel.py", line 107, in create_room
    map[x][y].blocked = False
IndexError: list index out of range

**Comment by Kumonorei** [comment]
Corrected, had mixed a variable for room height with room width, this is also responsible for the other bug of rooms generating at the edge of the map and having no wall. Corrected in next update.
